# Site settings
title: Musings On Data
header-img: img/home-bg.jpg
email: clint.howard92@gmail.com
copyright_name: 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  clinthoward
facebook_username:  
email_username:  clint.howard92@gmail.com
linkedin_username: clint-howard-5a29b927

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-85406922-1

author :
  name : Clint Howard
  email : clint.howard92@gmail.com
  github : clinthoward
  linkedin: clint-howard-5a29b927

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

layout: default
comments: true
