# Site settings
title: Title
author: Ammar Abdalrahem
header-img: img/home-bg.jpg
email: ammar.abdalrahem@outlook.com
copyright_name:
description: "Personal website for Ammar Abdalrahem"
baseurl: ""
url: "https://ammarabdalrahem.github.io"
twitter_username:
github_username:  
facebook_username:
email_username:  ammar.abdalrahem@outlook.com
linkedin_username: 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
#google_tracking_id: 
google_analytics: 

author :
  name : Ammar Abdalrahem
  email : ammar.abdalrahem@outlook.com
  github : 
  linkedin: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 100
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-sitemap, jekyll-paginate, jekyll-feed]

layout: default
comments: true
